---
- hosts: all
  become: yes
  tasks:
    - name: Criação de Usuário suporte
      ansible.builtin.user:
        name: suporte
        comment: suporte
        uid: 5000
        group: root
        